sudo: required
os:
- linux
services:
- docker
language: go
go:
- 1.12.x
- 1.11.x
jobs:
  include:
  - stage: build
    script: make build
  - stage: check
    script: make check
  - stage: unit-test
    script: make unit-test
  - stage: deploy
    script: make deploy
    if: branch = master
env:
  global:
    secure: "V/RBaI5uC5S/vZHB0Rcov346ge5EA0sAo5SL+uIPDrTzoWxiS8xody/zXbFk99ybBYljWsA5Km80j0iomC2uIiWFlgn5DOXxUgtYgovuXd8DMH5RyJss2yqTJPFQvyYS68Vax3wNBEMlqcF/D1A3oq5/qxhsijauHEnItx8uRNynHsYsGI+qguYV1yxHK31DLfN0uxmn8OIjqWYkq38+zd/xjwpPef9PiMsVAP+BJ4t6iMulTVH19vaJslA3jcm8BErFTpuVnNUJDs8ChKWN2Lyr87dJglpnu9hLTZfbZ4Je0WsaVMfNaRtX5KtWTHOzQjhg4sMv96L2wya04e3J1fwndFFFW81pDBe6+Yaf09Nb3e2yFR6PjhP61H+FDGSkdvgc54Vif1t4o0UdmTrV0GxeoGf55Z909DVvTrzRyOO+QLSOS3aW3gz9tJHJfG5c0WS/xKIdPkO3CCHaQgmHdkGsewI1Iy8bnpyjZxSORDox48ObtZIYSWI4A8hDw2msKc9gU24f+VBJI6qRouVIJgMqiQjqvfdYEanQKlSM5+buWerPM4u4xvQxHyQLGVMNCcAS2HGiy5oBw9mkMfJcKfsFR12OiyQuyBO7+rq0mW3BzNW9pznPLFYQvAz1YmLxpZlqMhzI6B0QoiYH0H+xTj3EFRgcKD32UrJ6t7UQ0gU="
